### ISSUE TITLE
Phyton update

### ISSUE THREAD

**Issue by bandit45** [quasar1/boxeebox-xbmc#19]
Hello is it Possible to get an Phyton update on KODI for Boxee Box?
I wanted to use the Trakt.TV addon and it is not possible please have a look at the attached file.

[kodi.log.txt](https://github.com/quasar1/boxeebox-xbmc/files/764761/kodi.log.txt)

19:44:23 T:2976218000  NOTICE: -->Python Interpreter Initialized<--
19:45:07 T:2976218000   ERROR: /tmp/mnt/2A8F-E45B/portable_data/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              SNIMissingWarning
19:45:07 T:2976218000   ERROR: /tmp/mnt/2A8F-E45B/portable_data/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
19:45:08 T:2976218000   ERROR: No handlers could be found for logger "traktapi"

Thank you very much for a great job to get Kodi on Boxee Box alive.

**Comment by quasar1** [comment]
Hi,
Python is a pain to get to cross-compile, it would probably require several days or weeks and even then it might not cross-compile. many patches and workarounds are generally needed. The Python version we have was introduced by Quarnster who started all this, he managed to get it to cross-compile eventually. It's not a case of just upgrading to the new version, the source code is cross-complied and usually has a large number of changes which means it won't cross-compile without loads of errors to fix.
This doesn't stop anybody trying for themselves, be warned, cross-compiling is the most difficult form of compilation. I know because I have spent thousands of hours doing it so far, not many are up to the continual hurdles put in place when you get an error. 
At the moment I do not have the time or inclination to look at this, especially for one add-on, I don't think that add-on worked before on Boxee XBMC/Kodi anyway, try an older version of that add-on I think it didn't work if my memory serves me well.. 
EDIT:
Just checked and this add-on is not compatible with Kodi Helix 14, only Isengard 15 and upwards..
http://kodi.wiki/view/Add-on:Trakt
If its just Python that needs updating and the TLS cert function enabled it could be possible if someone wants to look into it, as long as it doesn't rely on other things which are exclusively in Isengard...

**Comment by bandit45** [comment]
Hello,

thanks for your fast replie.
I've haven't known that it is such a pain in the ass.
There are also other addons next to trakt.tv which will not work because of the outdated phyton e.g. 
the addon mediathek which requires at least phyton 2.7.9.
The reason is the TLSv with SNI which is enabled in phyton 2.7.9 and up. 
So I would guess that is realy only the TLS function.
I'm can maybee help if anybody need assistance in programming cobol or dialog system but on other programing languages I'm lost.
I really hope somebody can help.
Thanks.

**Comment by quasar1** [comment]
Well I thought I'd have a quick look and I found a cross-compile patch, did some adjustments not expecting any luck and to my surprise it complied. I did notice errors but that is normal, it had some errors before but not serious.
I have a upgrade for you, backup your original folder and copy these files over your existing installation..
https://www.sendspace.com/file/sjs9cf

This might break existing add-ons, may be unstable etc.
The add-ons you mention I haven't tried, so may require other work but I may be able to fix that,,, just need feedback on the Python upgrade. For me Kodi loads, I have tried a few add-ons and they work fine so far, time will tell.
If this goes well i will do another Kodi release.

**Comment by bandit45** [comment]
Thank you very much for the great work you did und still do.
I really appreciate it.
I made a backup from my existing system and afterwards I copied all the contents of the zip file onto the sd-card. On my first test KODI is starting and it looks ok.
One thing which was working bevore is the weather plugin which is not working anymore.
I use the yahoo! weather plugin version. I tried another location, but the yahoo! weather addon won't find the location i put in. I will try another weather addon.
I tried also to install the addon mediatheken and there is still an error which tells there should bee a newer phyton version installed than 2.7.9. also I copied all the contents from your zip file which you provided, so there should be phyton in version 2.7.10 on the sd-card.
I also tried to get the Trakt.tv addon to work and yes it is working!!!!
Great job!!!!! Thank you so much!!!
I also attached a new kodi.log maybee it is possible to solve the yahoo weather problem.
Also I think KODi is reacting a litte bit slower than bevore.
[kodi.log.txt](https://github.com/quasar1/boxeebox-xbmc/files/775108/kodi.log.txt)

I tried other weather addons but there is not one addon really working.
Only the open weather map addon is working but displays wrong data and also the icon on the main Kodi screen isn't working anymore.
Also the slow reacting of Kodi changed it is now running fine, maybee it was becaus of the first start and was looking for updates.

Some other addons also stopped working because of PythonToCppException and SSL: CERTIFICATE_VERIFY_FAILED please see attaches KODI.log.new.txt.
[kodi.log.new.txt](https://github.com/quasar1/boxeebox-xbmc/files/775317/kodi.log.new.txt)

**Comment by quasar1** [comment]
The yahoo weather add-on broke because of a linker error, change libexpat.so to libexpat.so.1
This error broke other add-ons too.

The other error "PythonToCppException and SSL: CERTIFICATE_VERIFY_FAILED" I have fixed partially but I will try to get full SSL cert validation working. What I have done so far should in theory work but doesn't so I am chasing this out... only time will tell if I can fix it, we'll see.

Kodi does appear to boot quicker for me, this may be due to Python being a newer and more mature/stable version. I have tried compiling 2,7,13 and it failed early on so went back to 27.10.

BTW , I found and old version of Trakt.tv for Helix (version 3.0.4) https://github.com/trakt/script.trakt/releases/tag/3.0.4  Probably doesn't need the Python update, if all else fails.

**Comment by bandit45** [comment]
Thank you for your great job and your help on this.

I renamed libexpat.so to libexpat.so.1 an rebooted my boxee box but the yahoo! weather addon still don't refresh its data and isn't working.
I also tried to change the location but it doesn't matter which location I insert (e.g. "Erkner" or "Berlin") no results will bee displayed. Also when I use the location the yahoo! weather addon whith the location it was working before no result will be displayed. I attached the Kodi Log after the reboot.
[Uploading kodi.log.libexpat.so.1rename.reboot.txt…]()

I checked all my installed addons and so far all the others are seem to work exept these addons which throw the  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed error and the PythonToCppException.

I don't knwo how I can give you some suppot or help on these issue.
If you need any assistance please let me know and I try to give you a hand.

I really appreciate your good work on this. Thank you so much.

**Comment by quasar1** [comment]
Try this one, its with the SSL certs check disabled:
https://www.sendspace.com/file/wu4zfp

EDIT: SSL cert validation now working!
I had to add some code to the Boxee Hack startup line. All my add-ons which were working before are now working. Plus Icefilms which specifically requires SSL cert validation is now working.
I will compile a fresh build and post the link here in the next few hours.

**Comment by bandit45** [comment]
Oh cool!!!!
You are the best.....
I will test it on my boxee box as soon as the new build is available and let you know how it works.
I just closed this issue before by accident ;-)
I'm so happy right now....

**Comment by quasar1** [comment]
You will need to edit your **xbmc.sh** on your Boxee Box
/data/hack/misc/**xbmc.sh**
ADD - `SSL_CERT_FILE=${p}/system/certs/cacert.pem`
So it looks something like this...
`HOME=${p} GCONV_PATH=${p}/gconv SSL_CERT_FILE=${p}/system/certs/cacert.pem AE_ENGINE=active PYTHONPATH=${p}/python2.7:${p}/python2.7/lib-dynload PYTHONHOME=${p}/python2.7:${p}/python2.7/lib-dynload XBMC_HOME=${p} ${p}/${b} --standalone -p -l /var/run/lirc/lircd 2>>/tmp/xbmc.log`

**Comment by bandit45** [comment]
Hi,

can you give me a hint how to get acces to my Boxee Box /data/hack/misc/ to edit the xbmc.sh?
I can see my Boxee Box in the network area and when ich double click its openig but the only
thing I see is the sd-card with Kodi on it.
To get Kodi ti work on the Boxee Box I installed the boxee hacks http://boxeed.in/boxeeplus/install.zip
I checked the install.zip file but also there is no xbmc.sh file.

Thanks for your help.

I think I've got it...
I've downloaded putty portable and then connected to the BoxeeBox the default password for root is "secret". Than I copied the xbmc.sh to the sd-card and edited the xmbc.sh with the windows editor.
after that I copied the xbmc.sh back to /data/hack/misc/ forcing overwrite.
I hope this will work....

I just rebooted and KODI starts, but the yahoo weather addon still is not working for me.
When I check the kodi.log there are still Errors SSL: CERTIFICATE_VERIFY_FAILED....
I use still the first Python-2.7.10- For Kodi on BOXEE-Upgrade-TEST1 on my sd-card.

I copied the xbmc.sh again to the sd-card to check if overwriting was sucessful and yes it was.
In the xbmc.sh SSL_CERT_FILE=${p}/system/certs/cacert.pem is included.
But I still get these errors in the KODI.log maybee i broke some rights on the file.
The rights on xbmc.sh are right now rwxrwxrwx owner is root.

**Comment by quasar1** [comment]
Your **xbmc.sh** should be okay otherwise XBMC/Kodi wouldn't load at all.
You need a clean/fresh install with the working version...
**Python-2.7.10- For Kodi on BOXEE-Upgrade-TEST3-ssl-certs enabled**
https://www.sendspace.com/file/a0tcof

**Comment by bandit45** [comment]
Yes!!!!
You got it!!!
Trakt.TV is working, weather is working no SSL-Errors in the kodi.log....
Everyting seems to work nice.....
I really appreciate your work on this I'm so happy.....
Please keep our boxee boxes alive thank for a great job!!!!

**Comment by quasar1** [comment]
No problem, I think this is pretty stable so far, let me know if there are any issues, I will do a proper release if all seems to be well with this. For me Kodi loads quicker, which is a plus. This should give us a bit more life out of the old Boxee for a bit.... I did notice a slight increase in CPU usage, but if we use the default skins or ones which are less CPU intensive the Kodi experience should be  okay.

**Comment by bandit45** [comment]
Hello,

I've tested it whith differenet addons and all seems to work. Also shows, movies and pictures work quite good. Right now I don't see any issues. This version is also very stable, I don't had any losses.
For me some things maybee reacting a bit slower like if you search thru the addons, but this is ok.
It could bee that KODI loads a bit faster but I don't can tell realy maybee its because I have it installed on the sd-card on not on internal memory.
I will update my second Boxee Box during the weekend and will run the tests also there. 
Thanks for a great job that keeps our boxee boxes alive.

**Comment by quasar1** [comment]
I run Kodi on my NAS, 
If I get more time I will see what optimisations can be done.

**Comment by bandit45** [comment]
Hello,

I checked some other addons which where installed on my system and there are errors on the popcornflix addon. I attached the kodi.log if you can have a lock at this it would be great.
[kodi.log.popcornflix.txt](https://github.com/quasar1/boxeebox-xbmc/files/781229/kodi.log.popcornflix.txt)

**Comment by quasar1** [comment]
Try to open the URL's for that plugin, the are all dead links. 
`CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://redirect.superrepo.org/v7/addons/plugin.video.debilizator.tva/icon.png`
Did this work on the previous Python version?

**Comment by bandit45** [comment]
Hi,

i've just checked the link and this error is from another addon I tried to install which is not existing any mor, thats why the link is dead.

The error I meant is the following - I checked the popcornflix .com Video Addon (Autor: t1m, Version: 5.0.10) again:

18:34:31 T:2975853456  NOTICE: Thread LanguageInvoker start, auto delete: false
18:34:31 T:2975853456  NOTICE: -->Python Interpreter Initialized<--
18:35:02 T:2975853456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/tmp/mnt/00FE-0AAD/portable_data/addons/plugin.video.popcornflix/default.py", line 199, in <module>
                                                elif mode=='GV':  getVideo(p('url'))
                                              File "/tmp/mnt/00FE-0AAD/portable_data/addons/plugin.video.popcornflix/default.py", line 155, in getVideo
                                                a = json.loads(html)
                                              File "/tmp/mnt/00FE-0AAD/python2.7/json/__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "/tmp/mnt/00FE-0AAD/python2.7/json/decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/tmp/mnt/00FE-0AAD/python2.7/json/decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
18:35:02 T:3039344336   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.popcornflix/?url=09238c55-6fca-4d95-ab95-1e476103e01e&mode=GV]
18:35:05 T:2975853456  NOTICE: Thread BackgroundLoader start, auto delete: false

attached is the Kodi.log
I haven't updated my other Boxee Box I will check if the addon is working with the previous Python version.
[kodi.log.txt](https://github.com/quasar1/boxeebox-xbmc/files/783929/kodi.log.txt)

Thanks for your great support.

**Comment by quasar1** [comment]
That plugin isn't working on Kodi Jarvis on Windows in its newest version, its broken and looks like its not maintained any more.
Checkout mucky ducks repo, plenty of plugins on there that work. HD Box is good.

I got Python 2.7.13 working:
https://www.sendspace.com/file/krtwnj

**Comment by quasar1** [comment]
https://github.com/quasar1/boxeebox-xbmc/releases

**Comment by bandit45** [comment]
Thanks a lot for this great job.

I've tested the version which Python 2.7.13 during the weekend and it is working good and stable.
Great work!!! Thanks for the new release I will test it.

**Comment by quasar1** [comment]
The optimization changes I made to the project brought about a 6-7mb reduction in size to the kodi.bin. So worth testing the release.

**Comment by bandit45** [comment]
Hi,

currently I'm testing your new release on my both boxee boxes and it looks very good.
Everything is working nice. Thank you for your great work.

**Comment by quasar1** [comment]
New build released, no longer have to edit xbmc.sh to get the SSL Certs working, some improvements as well.
